// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero';
import { createBuilder } from '@rocicorp/zero';

const conversationTable = {
  name: 'conversation',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    title: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    updated_at: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    user_id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    current_model_id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    current_model_provider: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    current_model_name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
} as const;
const messageTable = {
  name: 'message',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    conversation_id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    content: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    role: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    updated_at: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    user_id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    web_search_enabled: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    attachments: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
} as const;
const conversationRelationships = {
  messages: [
    {
      sourceField: ['id'],
      destField: ['conversation_id'],
      destSchema: 'message',
      cardinality: 'many',
    },
  ],
} as const;
const messageRelationships = {
  conversation: [
    {
      sourceField: ['conversation_id'],
      destField: ['id'],
      destSchema: 'conversation',
      cardinality: 'one',
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    conversation: conversationTable,
    message: messageTable,
  },
  relationships: {
    conversation: conversationRelationships,
    message: messageRelationships,
  },
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "conversation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Conversation = Row<(typeof schema)['tables']['conversation']>;
/**
 * Represents a row from the "message" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<(typeof schema)['tables']['message']>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema;
  }
}
