/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as ChatImport } from './routes/_chat'
import { Route as ChatIndexImport } from './routes/_chat.index'
import { Route as ChatAccountImport } from './routes/_chat.account'
import { Route as ChatAboutImport } from './routes/_chat.about'
import { Route as ChatChatIdImport } from './routes/_chat.$chatId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  id: '/_chat',
  getParentRoute: () => rootRoute,
} as any)

const ChatIndexRoute = ChatIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)

const ChatAccountRoute = ChatAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ChatRoute,
} as any)

const ChatAboutRoute = ChatAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ChatRoute,
} as any)

const ChatChatIdRoute = ChatChatIdImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_chat/$chatId': {
      id: '/_chat/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof ChatChatIdImport
      parentRoute: typeof ChatImport
    }
    '/_chat/about': {
      id: '/_chat/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ChatAboutImport
      parentRoute: typeof ChatImport
    }
    '/_chat/account': {
      id: '/_chat/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ChatAccountImport
      parentRoute: typeof ChatImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexImport
      parentRoute: typeof ChatImport
    }
  }
}

// Create and export the route tree

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRoute
  ChatAboutRoute: typeof ChatAboutRoute
  ChatAccountRoute: typeof ChatAccountRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRoute,
  ChatAboutRoute: ChatAboutRoute,
  ChatAccountRoute: ChatAccountRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ChatRouteWithChildren
  '/auth': typeof AuthRoute
  '/$chatId': typeof ChatChatIdRoute
  '/about': typeof ChatAboutRoute
  '/account': typeof ChatAccountRoute
  '/': typeof ChatIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/$chatId': typeof ChatChatIdRoute
  '/about': typeof ChatAboutRoute
  '/account': typeof ChatAccountRoute
  '/': typeof ChatIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_chat': typeof ChatRouteWithChildren
  '/auth': typeof AuthRoute
  '/_chat/$chatId': typeof ChatChatIdRoute
  '/_chat/about': typeof ChatAboutRoute
  '/_chat/account': typeof ChatAccountRoute
  '/_chat/': typeof ChatIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/auth' | '/$chatId' | '/about' | '/account' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/$chatId' | '/about' | '/account' | '/'
  id:
    | '__root__'
    | '/_chat'
    | '/auth'
    | '/_chat/$chatId'
    | '/_chat/about'
    | '/_chat/account'
    | '/_chat/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  AuthRoute: typeof AuthRoute
}

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  AuthRoute: AuthRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_chat",
        "/auth"
      ]
    },
    "/_chat": {
      "filePath": "_chat.tsx",
      "children": [
        "/_chat/$chatId",
        "/_chat/about",
        "/_chat/account",
        "/_chat/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/_chat/$chatId": {
      "filePath": "_chat.$chatId.tsx",
      "parent": "/_chat"
    },
    "/_chat/about": {
      "filePath": "_chat.about.tsx",
      "parent": "/_chat"
    },
    "/_chat/account": {
      "filePath": "_chat.account.tsx",
      "parent": "/_chat"
    },
    "/_chat/": {
      "filePath": "_chat.index.tsx",
      "parent": "/_chat"
    }
  }
}
ROUTE_MANIFEST_END */
